version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2-buster-node
        environment:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: Moonlight-19
      - image: circleci/postgres:13
        environment:
          POSTGRES_USER: Moonlight-19
          POSTGRES_DB: Moonlight-19_test
          POSTGRES_PASSWORD: $DOCKERHUB_PASSWORD
    executor: ruby/default
    steps:
      - checkout
      # Restore bundle cache
      - restore_cache:
          keys:
            - Moonlight-19-{{ checksum "Gemfile.lock" }}
      - run:
          name: Install dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      # Store bundle cache
      - save_cache:
          key: Moonlight-19-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      # Wait for DB
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Database Setup
          command: |
            bundle exec rails db:create db:schema:load --trace
            bundle exec rails db:migrate
      - run:
          name: Minitest
          command: bin/rails test


